# -*- coding: utf-8 -*-
"""Furniture_Sales_Forecast.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/177SOC7aKfXkPWWFLng2apGmRgKS0bHxh
"""

#Importing packages
import numpy as np
import matplotlib.pyplot as plt
import warnings
warnings.filterwarnings("ignore")
plt.style.use('fivethirtyeight')
import pandas as pd
import itertools
import statsmodels.api as sm
import matplotlib
matplotlib.rcParams['axes.labelsize'] = 14
matplotlib.rcParams['xtick.labelsize'] = 12
matplotlib.rcParams['ytick.labelsize'] = 12
matplotlib.rcParams['text.color'] = 'k'

"""# **Importing Data**"""

# from google.colab import files
# uploaded = files.upload()
import io
df = pd.read_excel('store.xls')

df['Order Date'].min(), df['Order Date'].max()

"""# **Data Pre-processing**"""

#Taking a new dataframe with only Order Date and Sales columns.
df1 = df[['Order Date', 'price']]
#Sorting the dataframe by order date
df = df.sort_values('Order Date')
#Inspecting for missing values
df.isnull().sum()

df2 = df1.groupby('Order Date')['price'].sum().reset_index()

df2.head(10)

df2 = df2.set_index('Order Date')
df2.index

y = df2['price'].resample('MS').mean()
y.head(5)

"""# **Visualizing Sales Data**"""

y.plot(figsize=(15, 6))
plt.show()

from pylab import rcParams
rcParams['figure.figsize'] = 18, 8
decomposition = sm.tsa.seasonal_decompose(y, model='additive')
fig = decomposition.plot()
plt.show()

"""# **Time Series Forecasting With Arima**"""

#Setting seasonality, trend and noise parameters 
p = d = q = range(0, 2)
pdq = list(itertools.product(p, d, q))
seasonal_pdq = [(x[0], x[1], x[2], 12)for x in list(itertools.product(p, d, q))]

for param in pdq:
    for param_seasonal in seasonal_pdq:
        try:
            mod = sm.tsa.statespace.SARIMAX(y, order=param,
                                            seasonal_order=param_seasonal,
                                            enforce_stationarity=False,
                                            enforce_invertibility=False)
            results = mod.fit()
            print('ARIMA{}x{}12 - AIC:{}'.format(param, param_seasonal, results.aic))
        except:
            continue

mod = sm.tsa.statespace.SARIMAX(y,
                                order=(1, 1, 1),
                                seasonal_order=(1, 1, 0, 12),
                                enforce_stationarity=False,
                                enforce_invertibility=False)
results = mod.fit()
print(results.summary().tables[1])
results.plot_diagnostics(figsize=(16, 8))
plt.show()

"""# **Model Validation**"""

pred = results.get_prediction(start=pd.to_datetime('2017-01-01'), dynamic=False)
pred_ci = pred.conf_int()
ax = y['2014':].plot(label='observed')
pred.predicted_mean.plot(ax=ax, label='One-step ahead Forecast', alpha=1, figsize=(18, 7))
ax.fill_between(pred_ci.index,
                pred_ci.iloc[:, 0],
                pred_ci.iloc[:, 1], color='k', alpha=.2)
ax.set_xlabel('Date')
ax.set_ylabel('Furniture Sales')
plt.legend()
plt.show()

y_forecasted = pred.predicted_mean
y_truth = y['2014-01-01':]
mse = ((y_forecasted - y_truth) ** 2).mean()
print("MSE = ",mse)
rmse = format(round(np.sqrt(mse), 2))
print("RMSE = ",rmse)

"""# **Forecasting Furniture Sales**"""

pred_uc = results.get_forecast(steps=70)
pred_ci = pred_uc.conf_int()
ax = y.plot(label='observed', figsize=(14, 7))
pred_uc.predicted_mean.plot(ax=ax, label='Forecast')
ax.fill_between(pred_ci.index,
                pred_ci.iloc[:, 0],
                pred_ci.iloc[:, 1], color='k', alpha=.25)
ax.set_xlabel('Date')
ax.set_ylabel('Furniture Sales')
plt.legend()
plt.show()

date=input("Enter date in format yyyy-mm-01")
x=pred_ci.loc[date,'lower price']
x

y=pred_ci.loc[date,'upper price']
y